codecov:
  token: 0317610a-61dd-4c36-81ac-3e16afee1e7f
  require_ci_to_pass: false
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        target: 80%
        threshold: 5%
        base: auto
    patch:
      default:
        target: 80%
        threshold: 5%
        base: auto

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false

ignore:
  - "docs/"
  - "examples/"
  - "*.md"
  - "*.txt"
  - "*.yml"
  - "*.yaml"
  - "*.toml"
  - "*.lock"
  - "flake.lock"
  - "result*"
  - "tmp/"
  - "coverage-tmp/"
  - "scripts/testing/"
  - "config/"
  - "modules/templates/"
