# Treefmt configuration for nix-mox project
# This file defines formatting rules for various file types

[global]
# Project root file to identify the project
projectRootFile = "flake.nix"

# Exclude certain directories and files
excludes = [
  "result",
  "result-*",
  ".git",
  ".github",
  "node_modules",
  "*.min.js",
  "*.min.css",
  "*.lock",
  "flake.lock",
  "tmp",
  "tmp-*",
  "version",
  "sbom",
  "coverage-tmp",
  "scripts",
]

# Nix code formatting
[formatter.nix]
command = "nixpkgs-fmt"
includes = ["*.nix"]

# Shell script formatting
[formatter.shell]
command = "shfmt"
options = ["-i", "2", "-ci", "-sr", "-w"]
includes = ["*.sh", "*.bash", "*.zsh"]

# Shell script linting
[formatter.shellcheck]
command = "shellcheck"
options = ["--color=always", "--shell=bash", "--external-sources"]
includes = ["*.sh", "*.bash", "*.zsh"]

# Markdown formatting
[formatter.markdown]
command = "prettier"
options = ["--parser", "markdown", "--prose-wrap", "always", "--print-width", "80"]
includes = ["*.md", "*.mdx"]

# JSON formatting
[formatter.json]
command = "prettier"
options = ["--parser", "json", "--print-width", "80"]
includes = ["*.json"]

# YAML formatting
[formatter.yaml]
command = "prettier"
options = ["--parser", "yaml", "--print-width", "80"]
includes = ["*.yml", "*.yaml"]

# JavaScript/TypeScript formatting
[formatter.javascript]
command = "prettier"
options = [
  "--parser", "typescript",
  "--print-width", "80",
  "--semi", "true",
  "--single-quote", "true",
  "--trailing-comma", "es5"
]
includes = ["*.js", "*.ts", "*.jsx", "*.tsx"]

# CSS/SCSS formatting
[formatter.css]
command = "prettier"
options = ["--parser", "css", "--print-width", "80"]
includes = ["*.css", "*.scss", "*.sass"]

# HTML formatting
[formatter.html]
command = "prettier"
options = ["--parser", "html", "--print-width", "80"]
includes = ["*.html", "*.htm"]

# Python formatting
[formatter.python]
command = "black"
options = ["--line-length", "88", "--target-version", "py39"]
includes = ["*.py"]

# Rust formatting
[formatter.rust]
command = "rustfmt"
options = ["--edition", "2021"]
includes = ["*.rs"]

# Go formatting
[formatter.go]
command = "gofmt"
options = ["-w", "-s"]
includes = ["*.go"]

# Nushell formatting - Disabled due to ANSI color code conflicts
# [formatter.nushell]
# command = "nufmt"
# includes = ["*.nu"]
