global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['nixos-vm:9100']
  - job_name: 'windows'
    static_configs:
      - targets: ['windows-vm:9182']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 