# Personal User Configuration
# Generated by unified setup script

{ config, pkgs, ... }:

{
  # System user configuration
  users.users.droo = {
    isNormalUser = true;
    description = "droo";
    extraGroups = [ "wheel" "networkmanager" "video" "audio" ];
    shell = pkgs.bash;
  };

  # System configuration
  networking.hostName = "nixos";
  time.timeZone = "UTC";

  # Enable common services
  services.openssh.enable = true;
  # X11 and desktop environment configured in common.nix to avoid conflicts

  # Git configuration
  programs.git = {
    enable = true;
    config = {
      user.name = "droo";
      user.email = "user@example.com";
      init.defaultBranch = "main";
    };
  };

  # Basic packages
  environment.systemPackages = with pkgs; [
    wget curl git vim nano htop firefox
  ];
}