use serde_json::Value;

pub fn dark_theme() -> Value {
    json!({
        "name": "nix-mox Dark",
        "type": "dark",
        "colors": {
            "background": "#1a1a1a",
            "foreground": "#e6e6e6",
            "accent": "#00d4aa",
            "accent_foreground": "#ffffff",
            "border": "#404040",
            "border_variant": "#2a2a2a",
            "panel_background": "#2a2a2a",
            "panel_border": "#404040",
            "editor_background": "#1a1a1a",
            "editor_foreground": "#e6e6e6",
            "editor_cursor": "#00d4aa",
            "editor_selection": "#404040",
            "editor_inactive_selection": "#2a2a2a",
            "editor_indent_guide": "#404040",
            "editor_wrap_guide": "#2a2a2a",
            "editor_whitespace": "#404040",
            "editor_line_number": "#808080",
            "editor_active_line_number": "#e6e6e6",
            "editor_gutter": "#1a1a1a",
            "editor_gutter_background": "#1a1a1a",
            "terminal_background": "#1a1a1a",
            "terminal_foreground": "#e6e6e6",
            "terminal_cursor": "#00d4aa",
            "terminal_selection": "#404040",
            "terminal_ansi_black": "#1a1a1a",
            "terminal_ansi_red": "#ff6b6b",
            "terminal_ansi_green": "#51cf66",
            "terminal_ansi_yellow": "#ffd43b",
            "terminal_ansi_blue": "#74c0fc",
            "terminal_ansi_magenta": "#da77f2",
            "terminal_ansi_cyan": "#00d4aa",
            "terminal_ansi_white": "#e6e6e6",
            "terminal_ansi_bright_black": "#404040",
            "terminal_ansi_bright_red": "#ff8787",
            "terminal_ansi_bright_green": "#69db7c",
            "terminal_ansi_bright_yellow": "#ffe066",
            "terminal_ansi_bright_blue": "#91a7ff",
            "terminal_ansi_bright_magenta": "#e599f7",
            "terminal_ansi_bright_cyan": "#00d4aa",
            "terminal_ansi_bright_white": "#ffffff",
            "scrollbar_thumb": "#404040",
            "scrollbar_track": "#1a1a1a",
            "tooltip_background": "#2a2a2a",
            "tooltip_border": "#404040",
            "status_bar_background": "#2a2a2a",
            "status_bar_foreground": "#e6e6e6",
            "status_bar_border": "#404040",
            "title_bar_background": "#2a2a2a",
            "title_bar_foreground": "#e6e6e6",
            "title_bar_border": "#404040",
            "tab_active_background": "#1a1a1a",
            "tab_active_foreground": "#e6e6e6",
            "tab_active_border": "#00d4aa",
            "tab_inactive_background": "#2a2a2a",
            "tab_inactive_foreground": "#808080",
            "tab_inactive_border": "#404040",
            "button_background": "#404040",
            "button_foreground": "#e6e6e6",
            "button_border": "#404040",
            "button_hover_background": "#505050",
            "button_hover_foreground": "#ffffff",
            "button_hover_border": "#00d4aa",
            "input_background": "#2a2a2a",
            "input_foreground": "#e6e6e6",
            "input_border": "#404040",
            "input_focus_border": "#00d4aa",
            "dropdown_background": "#2a2a2a",
            "dropdown_foreground": "#e6e6e6",
            "dropdown_border": "#404040",
            "dropdown_hover_background": "#404040",
            "dropdown_hover_foreground": "#ffffff",
            "dropdown_hover_border": "#00d4aa"
        },
        "syntax": {
            "keyword": "#ff6b6b",
            "function": "#74c0fc",
            "string": "#51cf66",
            "number": "#ffd43b",
            "boolean": "#da77f2",
            "comment": "#808080",
            "operator": "#e6e6e6",
            "variable": "#00d4aa",
            "constant": "#ff8787",
            "type": "#91a7ff",
            "namespace": "#e599f7",
            "module": "#69db7c",
            "error": "#ff6b6b",
            "warning": "#ffd43b",
            "info": "#74c0fc",
            "hint": "#00d4aa"
        }
    })
}

pub fn light_theme() -> Value {
    json!({
        "name": "nix-mox Light",
        "type": "light",
        "colors": {
            "background": "#ffffff",
            "foreground": "#1a1a1a",
            "accent": "#00d4aa",
            "accent_foreground": "#ffffff",
            "border": "#e0e0e0",
            "border_variant": "#f0f0f0",
            "panel_background": "#f8f8f8",
            "panel_border": "#e0e0e0",
            "editor_background": "#ffffff",
            "editor_foreground": "#1a1a1a",
            "editor_cursor": "#00d4aa",
            "editor_selection": "#e0e0e0",
            "editor_inactive_selection": "#f0f0f0",
            "editor_indent_guide": "#e0e0e0",
            "editor_wrap_guide": "#f0f0f0",
            "editor_whitespace": "#e0e0e0",
            "editor_line_number": "#808080",
            "editor_active_line_number": "#1a1a1a",
            "editor_gutter": "#ffffff",
            "editor_gutter_background": "#ffffff",
            "terminal_background": "#ffffff",
            "terminal_foreground": "#1a1a1a",
            "terminal_cursor": "#00d4aa",
            "terminal_selection": "#e0e0e0",
            "terminal_ansi_black": "#1a1a1a",
            "terminal_ansi_red": "#e03131",
            "terminal_ansi_green": "#37b24d",
            "terminal_ansi_yellow": "#f59f00",
            "terminal_ansi_blue": "#1971c2",
            "terminal_ansi_magenta": "#c2255c",
            "terminal_ansi_cyan": "#00d4aa",
            "terminal_ansi_white": "#ffffff",
            "terminal_ansi_bright_black": "#868e96",
            "terminal_ansi_bright_red": "#fa5252",
            "terminal_ansi_bright_green": "#51cf66",
            "terminal_ansi_bright_yellow": "#ffd43b",
            "terminal_ansi_bright_blue": "#74c0fc",
            "terminal_ansi_bright_magenta": "#da77f2",
            "terminal_ansi_bright_cyan": "#00d4aa",
            "terminal_ansi_bright_white": "#f8f9fa",
            "scrollbar_thumb": "#e0e0e0",
            "scrollbar_track": "#ffffff",
            "tooltip_background": "#f8f8f8",
            "tooltip_border": "#e0e0e0",
            "status_bar_background": "#f8f8f8",
            "status_bar_foreground": "#1a1a1a",
            "status_bar_border": "#e0e0e0",
            "title_bar_background": "#f8f8f8",
            "title_bar_foreground": "#1a1a1a",
            "title_bar_border": "#e0e0e0",
            "tab_active_background": "#ffffff",
            "tab_active_foreground": "#1a1a1a",
            "tab_active_border": "#00d4aa",
            "tab_inactive_background": "#f8f8f8",
            "tab_inactive_foreground": "#808080",
            "tab_inactive_border": "#e0e0e0",
            "button_background": "#e0e0e0",
            "button_foreground": "#1a1a1a",
            "button_border": "#e0e0e0",
            "button_hover_background": "#d0d0d0",
            "button_hover_foreground": "#000000",
            "button_hover_border": "#00d4aa",
            "input_background": "#f8f8f8",
            "input_foreground": "#1a1a1a",
            "input_border": "#e0e0e0",
            "input_focus_border": "#00d4aa",
            "dropdown_background": "#f8f8f8",
            "dropdown_foreground": "#1a1a1a",
            "dropdown_border": "#e0e0e0",
            "dropdown_hover_background": "#e0e0e0",
            "dropdown_hover_foreground": "#000000",
            "dropdown_hover_border": "#00d4aa"
        },
        "syntax": {
            "keyword": "#e03131",
            "function": "#1971c2",
            "string": "#37b24d",
            "number": "#f59f00",
            "boolean": "#c2255c",
            "comment": "#868e96",
            "operator": "#1a1a1a",
            "variable": "#00d4aa",
            "constant": "#fa5252",
            "type": "#74c0fc",
            "namespace": "#da77f2",
            "module": "#51cf66",
            "error": "#e03131",
            "warning": "#f59f00",
            "info": "#1971c2",
            "hint": "#00d4aa"
        }
    })
}

fn json!(value: serde_json::Value) -> serde_json::Value {
    value
}
