name: 'Setup Nix Environment'
description: 'Setup Nix with custom configuration for nix-mox'
inputs:
  nix-version:
    description: 'Nix version to install'
    required: false
    default: '2.19.2'
  extra-trusted-public-keys:
    description: 'Additional trusted public keys'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Install Nix
      shell: bash
      run: |
        echo "Installing Nix ${{ inputs.nix-version }}..."
        sh <(curl -L https://nixos.org/nix/install) --daemon --yes

        # Source nix environment
        . /etc/profile.d/nix.sh

        # Configure Nix
        mkdir -p /etc/nix
        cat > /etc/nix/nix.conf << EOF
        experimental-features = nix-command flakes
        accept-flake-config = true
        extra-trusted-public-keys = ${{ inputs.extra-trusted-public-keys }}
        EOF

        echo "Nix setup completed successfully"
