name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: cachix/install-nix-action@v31
        
      - name: Check flake
        run: |
          nix flake check --no-build
          
      - name: Build configuration
        run: |
          nix build .#nixosConfigurations.nixos.config.system.build.toplevel --dry-run
          
      - name: Check formatting
        run: |
          nix run .#fmt
