name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_packages:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    strategy:
      matrix:
        system: [x86_64-linux, aarch64-linux]
        nix-version: ['2.19.2', '2.20.1']
      fail-fast: false
    env:
      CI: true
      DISABLE_HEAVY_PACKAGES: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Check for Cachix Key
        id: cachix-key-check
        shell: bash
        run: |
          # Temporarily disable Cachix until credentials are properly configured
          echo "present=false" >> $GITHUB_OUTPUT
          echo "Cachix temporarily disabled - skipping Cachix operations"
          # if [ -n "${{ secrets.CACHIX_SIGNING_KEY }}" ] && [ -n "${{ secrets.CACHIX_AUTH_TOKEN }}" ]; then
          #   echo "present=true" >> $GITHUB_OUTPUT
          #   echo "Cachix credentials found"
          # else
          #   echo "present=false" >> $GITHUB_OUTPUT
          #   echo "Cachix credentials missing - skipping Cachix operations"
          # fi
      - name: Push to Cachix
        if: steps.cachix-key-check.outputs.present == 'true'
        uses: cachix/cachix-action@v16
        with:
          name: nix-mox
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        continue-on-error: true
      - name: Build lightweight packages first
        run: |
          echo "Building lightweight packages for ${{ matrix.system }}..."
          nix build .#proxmox-update .#nixos-flake-update --system ${{ matrix.system }} --accept-flake-config --timeout 1800
        continue-on-error: true
      - name: Build additional packages
        run: |
          echo "Building additional packages for ${{ matrix.system }}..."
          nix build .#install .#uninstall .#remote-builder-setup .#test-remote-builder --system ${{ matrix.system }} --accept-flake-config --timeout 1800
        continue-on-error: true
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nix-mox-${{ matrix.system }}-${{ matrix.nix-version }}
          path: result*
          if-no-files-found: ignore
        continue-on-error: true

  build_macos_packages:
    runs-on: macos-latest
    timeout-minutes: 60
    strategy:
      matrix:
        system: [x86_64-darwin, aarch64-darwin]
        nix-version: ['2.19.2', '2.20.1']
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Check for Cachix Key
        id: cachix-key-check
        shell: bash
        run: |
          # Temporarily disable Cachix until credentials are properly configured
          echo "present=false" >> $GITHUB_OUTPUT
          echo "Cachix temporarily disabled - skipping Cachix operations"
      - name: Push to Cachix
        if: steps.cachix-key-check.outputs.present == 'true'
        uses: cachix/cachix-action@v16
        with:
          name: nix-mox
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        continue-on-error: true
      - name: Build macOS packages
        run: |
          echo "Building macOS packages for ${{ matrix.system }}..."
          nix build .#homebrew-setup .#macos-maintenance .#xcode-setup .#security-audit --system ${{ matrix.system }} --accept-flake-config --timeout 1800
        continue-on-error: true
      - name: Build common packages
        run: |
          echo "Building common packages for ${{ matrix.system }}..."
          nix build .#install .#uninstall --system ${{ matrix.system }} --accept-flake-config --timeout 1800
        continue-on-error: true
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nix-mox-${{ matrix.system }}-${{ matrix.nix-version }}
          path: result*
          if-no-files-found: ignore
        continue-on-error: true

  test:
    needs: [build_packages, build_macos_packages]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Check for Cachix Key
        id: cachix-key-check
        shell: bash
        run: |
          # Temporarily disable Cachix until credentials are properly configured
          echo "present=false" >> $GITHUB_OUTPUT
          echo "Cachix temporarily disabled - skipping Cachix operations"
          # if [ -n "${{ secrets.CACHIX_SIGNING_KEY }}" ] && [ -n "${{ secrets.CACHIX_AUTH_TOKEN }}" ]; then
          #   echo "present=true" >> $GITHUB_OUTPUT
          #   echo "Cachix credentials found"
          # else
          #   echo "present=false" >> $GITHUB_OUTPUT
          #   echo "Cachix credentials missing - skipping Cachix operations"
          # fi
      - name: Push to Cachix
        if: steps.cachix-key-check.outputs.present == 'true'
        uses: cachix/cachix-action@v16
        with:
          name: nix-mox
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        continue-on-error: true
      - name: Run tests
        run: |
          # Set CI environment variable to disable NixOS configs
          export CI=true
          # Run flake check with timeout and accept flake config
          timeout 300 nix flake check --accept-flake-config --impure
        continue-on-error: true

      - name: Find and prepare coverage report
        if: always()
        run: |
          # Find the coverage file in the temporary directory
          COVERAGE_FILE=$(find /tmp -name "coverage.json" -path "*/nix-mox-tests/*" 2>/dev/null | head -1)
          if [ -n "$COVERAGE_FILE" ]; then
            echo "Found coverage file at: $COVERAGE_FILE"
            # Copy to a known location for upload
            mkdir -p coverage-tmp/nix-mox-tests
            cp "$COVERAGE_FILE" coverage-tmp/nix-mox-tests/coverage.json
            echo "Coverage file copied to coverage-tmp/nix-mox-tests/coverage.json"

            # Convert to codecov format
            nix develop --command nu -c "
              let coverage = (open 'coverage-tmp/nix-mox-tests/coverage.json' | from json)
              let pass_rate = ($coverage | get summary.pass_rate)
              let total_tests = ($coverage | get summary.total_tests)
              let passed_tests = ($coverage | get summary.passed_tests)

              # Create codecov-compatible format
              let codecov_report = {
                coverage: {
                  total: $total_tests
                  passed: $passed_tests
                  rate: $pass_rate
                  timestamp: (date now | into int)
                }
                results: ($coverage | get results | each { |test|
                  {
                    name: $test.name
                    status: $test.status
                    duration: $test.duration
                    category: $test.category
                  }
                })
              }

              $codecov_report | to json | save --force 'coverage-tmp/codecov.json'
            "
            echo "Codecov report generated at coverage-tmp/codecov.json"
          else
            echo "No coverage file found"
          fi

      - name: Upload test results to Codecov
        if: always()
        uses: codecov/codecov-action@v4
        with:
          files: coverage-tmp/codecov.json
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}

  coverage:
    needs: [test]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Run comprehensive coverage tests
        run: |
          # Set CI environment variable
          export CI=true
          export TEST_TEMP_DIR="/tmp/nix-mox-coverage"

          # Run tests with coverage tracking
          nix develop --command nu -c "
            source scripts/tests/run-tests.nu
            run ['--unit', '--integration']
          "

          # Generate coverage report
          nix develop --command nu -c "
            source scripts/tests/lib/test-coverage.nu
            let coverage = aggregate_coverage
            let report = {
              summary: {
                total_tests: $coverage.total_tests
                passed_tests: $coverage.passed_tests
                failed_tests: $coverage.failed_tests
                skipped_tests: $coverage.skipped_tests
                test_duration: $coverage.test_duration
                pass_rate: (if $coverage.total_tests == 0 { 0 } else { (($coverage.passed_tests | into float) / ($coverage.total_tests | into float) * 100) })
              }
              categories: $coverage.test_categories
              results: $coverage.test_results
            }

            $report | to json | save --force 'coverage-report.json'
          "

          echo "Coverage report generated"

      - name: Upload coverage report to Codecov
        if: always()
        uses: codecov/codecov-action@v4
        with:
          files: coverage-report.json
          flags: coverage
          name: codecov-coverage
          fail_ci_if_error: false
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build_packages, build_macos_packages, test, coverage]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Setup Cachix (optional)
        run: |
          if [ -n "${{ secrets.CACHIX_SIGNING_KEY }}" ] && [ -n "${{ secrets.CACHIX_AUTH_TOKEN }}" ]; then
            echo "Setting up Cachix..."
            if command -v cachix &> /dev/null; then
              cachix use nix-mox
            else
              echo "Cachix not available, skipping setup"
            fi
          else
            echo "Cachix credentials not set, skipping Cachix setup"
          fi
        continue-on-error: true
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            result-*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Nix
        uses: cachix/install-nix-action@v31

      - name: Show Nix version
        run: |
          nix --version

      - name: Run tests
        run: nix develop --command nu -c "source scripts/tests/run-tests.nu; run ['--unit']"

      - name: Generate Project Status Dashboard
        run: nix develop --command nu scripts/tools/project-dashboard.nu

      - name: Upload Project Dashboard Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: project-dashboard
          path: |
            tmp/dashboard.json
            tmp/dashboard.md

  build_heavy_packages:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      matrix:
        system: [x86_64-linux]
        nix-version: ['2.20.1']
      fail-fast: false
    env:
      CI: true
      # Allow heavy packages for this job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Check for Cachix Key
        id: cachix-key-check
        shell: bash
        run: |
          # Temporarily disable Cachix until credentials are properly configured
          echo "present=false" >> $GITHUB_OUTPUT
          echo "Cachix temporarily disabled - skipping Cachix operations"
      - name: Push to Cachix
        if: steps.cachix-key-check.outputs.present == 'true'
        uses: cachix/cachix-action@v15
        with:
          name: nix-mox
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        continue-on-error: true
      - name: Build heavy packages
        run: |
          echo "Building heavy packages for ${{ matrix.system }}..."
          # Build heavy packages individually with longer timeouts
          for pkg in vzdump-backup zfs-snapshot; do
            echo "Building $pkg..."
            if nix build .#$pkg --system ${{ matrix.system }} --accept-flake-config --timeout 7200; then
              echo "Successfully built $pkg"
            else
              echo "Failed to build $pkg - continuing with other packages"
            fi
          done
        continue-on-error: true
      - name: Upload heavy package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nix-mox-heavy-${{ matrix.system }}-${{ matrix.nix-version }}
          path: result*
          if-no-files-found: ignore
        continue-on-error: true
