name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        nix-channel: [nixos-unstable]

    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Setup Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Run tests
      run: |
        nix flake check

    - name: Find and upload coverage report
      run: |
        # Find the coverage file in the temporary directory
        COVERAGE_FILE=$(find /tmp -name "coverage.json" -path "*/nix-mox-tests/*" 2>/dev/null | head -1)
        if [ -n "$COVERAGE_FILE" ]; then
          echo "Found coverage file at: $COVERAGE_FILE"
          # Copy to a known location for upload
          mkdir -p coverage-tmp/nix-mox-tests
          cp "$COVERAGE_FILE" coverage-tmp/nix-mox-tests/coverage.json
          echo "Coverage file copied to coverage-tmp/nix-mox-tests/coverage.json"
        else
          echo "No coverage file found"
        fi

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage-tmp/nix-mox-tests/coverage.json
        if-no-files-found: ignore

    - name: Check test coverage
      run: |
        # Find the coverage file and check it
        COVERAGE_FILE=$(find /tmp -name "coverage.json" -path "*/nix-mox-tests/*" 2>/dev/null | head -1)
        if [ -n "$COVERAGE_FILE" ]; then
          echo "Checking coverage file: $COVERAGE_FILE"
          nix develop --command nu -c "
            let coverage = (open '$COVERAGE_FILE' | from json)
            let pass_rate = ($coverage | get summary.pass_rate)
            print 'Pass rate: ' + ($pass_rate | into string) + '%'
            if $pass_rate < 90 {
              error make { msg: 'Test coverage below 90%' }
            }
          "
        else
          echo "No coverage file found, skipping coverage check"
        fi
